# Generated by Django 5.0.9 on 2024-09-14 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_tipopluginmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamodel',
            options={'verbose_name': 'Categoria do Plugin', 'verbose_name_plural': 'Categoria do Plugin'},
        ),
        migrations.AlterModelOptions(
            name='tipopluginmodel',
            options={'verbose_name': 'Tipo do Plugin', 'verbose_name_plural': 'Tipo do Plugin'},
        ),
       
    ]
