# Generated by Django 5.0.9 on 2024-09-14 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_tipopluginmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamodel',
            options={'verbose_name': 'Categoria do Plugin', 'verbose_name_plural': 'Categoria do Plugin'},
        ),
        migrations.AlterModelOptions(
            name='tipopluginmodel',
            options={'verbose_name': 'Tipo do Plugin', 'verbose_name_plural': 'Tipo do Plugin'},
        ),
        migrations.CreateModel(
            name='ArtefatoPluginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('versao', models.CharField(max_length=50)),
                ('tipo_arquivo', models.CharField(max_length=50)),
                ('caminho_arquivo', models.CharField(max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artefato do Plugin',
                'verbose_name_plural': 'Artefatos do Plugin',
            },
        ),
    ]
