# Generated by Django 5.0.9 on 2024-09-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_artefatopluginmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artefatopluginmodel',
            table='infrastructure_artefato_plugin',
        ),
    ]
