# Generated by Django 5.0.9 on 2024-09-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_alter_artefatopluginmodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artefatopluginmodel',
            options={'verbose_name': 'Artefato do Plugin', 'verbose_name_plural': 'Artefatos do Plugin'},
        ),
        migrations.AlterModelOptions(
            name='categoriamodel',
            options={'verbose_name': 'Categoria do Plugin', 'verbose_name_plural': 'Categoria do Plugin'},
        ),
        migrations.AlterModelOptions(
            name='tipopluginmodel',
            options={'verbose_name': 'Tipo do Plugin', 'verbose_name_plural': 'Tipo do Plugin'},
        ),
    ]
