# Generated by Django 5.0.9 on 2024-09-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_pluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginmodel',
            name='caminho_arquivo',
            field=models.CharField(default='caminho/padrao', max_length=500),
            preserve_default=False,
        ),
    ]
