# Generated by Django 5.0.9 on 2024-09-16 22:59

import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('infrastructure', '0005_pluginmodel_caminho_arquivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginmodel',
            name='dependencias',
        ),
        migrations.RemoveField(
            model_name='pluginmodel',
            name='historico_modificacoes',
        ),
        migrations.RemoveField(
            model_name='pluginmodel',
            name='permissoes',
        ),
        migrations.RemoveField(
            model_name='pluginmodel',
            name='tags',
        ),
        migrations.CreateModel(
            name='DependenciaModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_dependencia', models.CharField(choices=[('plugin', 'Plugin'), ('biblioteca', 'Biblioteca'), ('serviço', 'Serviço'), ('outro', 'Outro')], default='plugin', max_length=50)),
                ('nome_dependencia', models.CharField(blank=True, max_length=255, null=True)),
                ('url_dependencia', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('dependencia_plugin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.pluginmodel')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_plugin_set', to='infrastructure.pluginmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dependência do Plugin',
                'verbose_name_plural': 'Dependências do Plugin',
                'db_table': 'infrastructure_dependencias_plugin',
            },
        ),
        migrations.CreateModel(
            name='HistoricoModificacoesModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_modificacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=255)),
                ('descricao_modificacao', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.pluginmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Modificações do Plugin',
                'verbose_name_plural': 'Históricos de Modificações dos Plugins',
                'db_table': 'infrastructure_historico_modificacoes_plugin',
            },
        ),
        migrations.CreateModel(
            name='PermissaoPluginModel',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissao_plugin_set', to='infrastructure.pluginmodel')),
            ],
            options={
                'verbose_name': 'Permissão de Plugin',
                'verbose_name_plural': 'Permissões de Plugin',
                'db_table': 'permissoes_plugin',
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='TagPluginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag de Plugin',
                'verbose_name_plural': 'Tags de Plugin',
                'db_table': 'infrastructure_tags_plugin',
            },
        ),
        migrations.CreateModel(
            name='TemplatePluginModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_template', models.CharField(max_length=255)),
                ('caminho_arquivo', models.CharField(max_length=255)),
                ('contexto_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_plugin_set', to='infrastructure.pluginmodel')),
            ],
            options={
                'verbose_name': 'Template de Plugin',
                'verbose_name_plural': 'Templates de Plugin',
                'db_table': 'infrastructure_template_plugin',
            },
        ),
        migrations.AddField(
            model_name='pluginmodel',
            name='templates',
            field=models.ManyToManyField(related_name='plugins', to='infrastructure.templatepluginmodel'),
        ),
        migrations.AddField(
            model_name='pluginmodel',
            name='dependencias',
            field=models.ManyToManyField(related_name='plugins', to='infrastructure.dependenciamodel'),
        ),
        migrations.AddField(
            model_name='pluginmodel',
            name='historico_modificacoes',
            field=models.ManyToManyField(related_name='plugins', to='infrastructure.historicomodificacoesmodel'),
        ),
        migrations.AddField(
            model_name='pluginmodel',
            name='permissoes',
            field=models.ManyToManyField(related_name='plugins', to='infrastructure.permissaopluginmodel'),
        ),
        migrations.AddField(
            model_name='pluginmodel',
            name='tags',
            field=models.ManyToManyField(related_name='plugins', to='infrastructure.tagpluginmodel'),
        ),
    ]
