# Generated by Django 5.0.9 on 2024-09-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_remove_pluginmodel_dependencias_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artefatopluginmodel',
            table='infrastructure_artefato_plugin',
        ),
        migrations.AlterModelTable(
            name='categoriamodel',
            table='infrastructure_categoria_plugin',
        ),
        migrations.AlterModelTable(
            name='dependenciamodel',
            table='infrastructure_dependencia_plugin',
        ),
        migrations.AlterModelTable(
            name='historicomodificacoesmodel',
            table='infrastructure_historico_modificacao_plugin',
        ),
        migrations.AlterModelTable(
            name='permissaopluginmodel',
            table='infrastructure_permissao_plugin',
        ),
        migrations.AlterModelTable(
            name='tagpluginmodel',
            table='infrastructure_tag_plugin',
        ),
        migrations.AlterModelTable(
            name='tipopluginmodel',
            table='infrastructure_tipo_plugin',
        ),
    ]
