# Generated by Django 5.0.9 on 2024-09-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_enderecomodel_localizacao_profissaomodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, choices=[], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customsite',
            name='status',
            field=models.CharField(blank=True, choices=[], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='permissaowebsite',
            name='status',
            field=models.CharField(blank=True, choices=[], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoafisicamodel',
            name='status',
            field=models.CharField(blank=True, choices=[], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pluginmodel',
            name='status',
            field=models.CharField(blank=True, choices=[], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(blank=True, choices=[], default=None, max_length=20, null=True),
        ),
    ]
