# Generated by Django 5.0.9 on 2024-09-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_alter_blog_status_alter_category_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisicamodel',
            name='bios',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pessoafisicamodel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='pessoafisicamodel',
            name='situacao',
            field=models.CharField(choices=[('adimplente', 'Adimplente'), ('atraso', 'Pagamento em Atraso'), ('suspenso', 'Suspenso'), ('renegociacao', 'Com Renegociação')], default='adimplente', max_length=255),
        ),
    ]
