# Generated by Django 5.0.9 on 2024-09-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_pessoafisicamodel_bios_pessoafisicamodel_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisicamodel',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pessoafisicamodel',
            name='primeiro_nome',
        ),
        migrations.RemoveField(
            model_name='pessoafisicamodel',
            name='sobrenome',
        ),
        migrations.AlterField(
            model_name='pessoafisicamodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='pessoafisicamodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sobrenome'),
        ),
    ]
