# Generated by Django 5.0.9 on 2024-09-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0013_categoriaplugin_remove_tag_blog_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriaplugin',
            table='infrastructure_categoria_plugin',
        ),
    ]
