# Generated by Django 5.0.9 on 2024-09-25 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0015_categoriaplugin_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioReacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reacao_tipo', models.CharField(max_length=20)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_reacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reação ao Comentário',
                'verbose_name_plural': 'Reações aos Comentários',
                'db_table': 'infrastructure_reacao_comentario',
                'ordering': ['-data_reacao'],
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='reacoes',
        ),
        migrations.RemoveField(
            model_name='comentariopost',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='comentariopost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comentariopost',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comentariopost',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='comentariopost',
            name='inactivated_at',
        ),
        migrations.RemoveField(
            model_name='comentariopost',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='comentariopost',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='comentariopost',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='comentariopost',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='pessoafisicamodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentariopost',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentariopost',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='infrastructure.localizacao'),
        ),
        migrations.AddField(
            model_name='pessoafisicamodel',
            name='pessoa_fisica_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentariopost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='infrastructure.post'),
        ),
        migrations.AlterField(
            model_name='comentariopost',
            name='status',
            field=models.CharField(default='aguardando', max_length=20),
        ),
        migrations.CreateModel(
            name='ReacaoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='reacoes/icones/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalhe da Reação',
                'verbose_name_plural': 'Detalhes das Reações',
                'db_table': 'infrastructure_reacao_detalhe',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTipo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[], default=None, max_length=20, null=True)),
                ('usuario_tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Usuário',
                'verbose_name_plural': 'Tipos de Usuário',
                'db_table': 'infrastructure_usuario_tipo',
            },
        ),
        migrations.DeleteModel(
            name='ReacaoComentario',
        ),
        migrations.DeleteModel(
            name='ReacaoDetalhe',
        ),
    ]
